// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuL-BH-80uP6-gsXZE5xEFpvwb4iYYKk',
    appId: '1:1080146946499:web:a0f88ed6a340cbf122b576',
    messagingSenderId: '1080146946499',
    projectId: 'blog-e7a44',
    authDomain: 'blog-e7a44.firebaseapp.com',
    storageBucket: 'blog-e7a44.appspot.com',
    measurementId: 'G-29RWL6QG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyvqwuPk_xoAbipCV007DfMevzeulhI9U',
    appId: '1:1080146946499:android:290f71c5e2a7ca4722b576',
    messagingSenderId: '1080146946499',
    projectId: 'blog-e7a44',
    storageBucket: 'blog-e7a44.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMuL-BH-80uP6-gsXZE5xEFpvwb4iYYKk',
    appId: '1:1080146946499:web:547157318d22bcd222b576',
    messagingSenderId: '1080146946499',
    projectId: 'blog-e7a44',
    authDomain: 'blog-e7a44.firebaseapp.com',
    storageBucket: 'blog-e7a44.appspot.com',
    measurementId: 'G-Z6V4LW46YX',
  );
}
